# Generated by Django 2.2.6 on 2020-03-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
