# Generated by Django 2.2.6 on 2020-04-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0009_jobinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='experience',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='ApplicationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes')),
                ('score', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('interview_info', models.CharField(blank=True, default=None, max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.JobInfo')),
            ],
        ),
    ]
