# Generated by Django 2.2.6 on 2020-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20200405_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='interview_info',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
