# Generated by Django 2.2.6 on 2020-04-05 16:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0011_auto_20200405_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationinfo',
            unique_together={('candidate', 'job')},
        ),
    ]
