# Generated by Django 2.2.6 on 2020-04-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_auto_20200405_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinfo',
            name='interview_info',
            field=models.CharField(blank=True, default='None', max_length=150),
        ),
    ]
