# Generated by Django 2.2.6 on 2020-04-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20200406_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationinfo',
            name='interview_info',
        ),
    ]
